### ISSUE TITLE
Commands not working

### ISSUE THREAD

**Issue by Tobimasuu** [BluSpring/Nicknamer#3]
Hello,

I attempted to use the commands you said would work in the readme file, but it did not show up at all. Any help with this would be nice.

Thanks,
Tobi

**Comment by BluSpring** [comment]
Hey Tobi,

This was entirely my bad! I fixed this a couple months ago, but I completely forgot to update the mod on Modrinth and CurseForge.
You should see updated versions of the mod on Modrinth by now, not sure about CurseForge though, where it should be working now.
