### ISSUE TITLE
Cannot set pronoun color.

### ISSUE THREAD

**Issue by KateReller** [BluSpring/Nicknamer#4]
Command returns `The color given is invalid!` every time I try to give it a hex value.

Logs: https://mclo.gs/e8ck574

**Comment by BluSpring** [comment]
Ah shit, that's my bad

It's supposed to handle hex values with "#hexvalue", but the string argument I'm using doesn't seem to like starting with #. whoops.

**Comment by BluSpring** [comment]
Fixed with release 1.1.1+1.19 and 1.1.1+1.19.3.
