### ISSUE TITLE
Inconsistent settings order in nicknamer config

### ISSUE THREAD

**Issue by HollowMisty** [BluSpring/Nicknamer#5]
v1.1.1+1.19.3

In-game Name Format and Chat Format settings are ordered

Pronouns & Nicknames Visible
Nicknames Visible
Pronouns Visible
None Visible

Player List Name Format settings are ordered

Pronouns & Nicknames Visible
Pronouns Visible
Nicknames Visible
None Visible

**Comment by BluSpring** [comment]
Fixed in v1.1.2+1.20.4, if you want me to backport it to older MC versions lmk :)
