### ISSUE TITLE
Game crashes when trying to change the colour of pronouns

### ISSUE THREAD

**Issue by AshleyRedstone** [BluSpring/Nicknamer#6]
[crash-2024-01-08_08.19.51-client.txt](https://github.com/BluSpring/Nicknamer/files/13860850/crash-2024-01-08_08.19.51-client.txt)

**Comment by BluSpring** [comment]
i thought i tested this on 1.20.4 already specifically to see if it breaks or not, my god, alright, hold on

**Comment by BluSpring** [comment]
Fixed in v1.1.2 :)
